### ISSUE TITLE
add ofEnableDepthTest() to example

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#11]
it's a small thing but the example-basic should have depth test turned on which it draws the OF logos and turned off before it draws the camera image and the 3d overlay text.   by default OF has depth testing turned off.  the depth buffer is enabled in main.mm but it's still not enough.

ie: 

    ofDisableDepthTest();
    processor->draw();   // this is 2d drawing
    ofEnableDepthTest();
    if (session.currentFrame){
         ....  // draw 3d stuff
    }
    ofDisableDepthTest();
    // more 2d drawing (overlay txt)

**Comment by sortofsleepy** [comment]
Good catch! I completely didn't think of that. Will get to fixing it up later this weekend

**Comment by sortofsleepy** [comment]
I've added the necessary changes, closing this
