### ISSUE TITLE
description of manual steps if you use project generator

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#12]
if you use the OF pg to update an ofxArKit project (for example, to update an example adding w/ an addon, etc) there are some settings that get overwritten -- it might be useful to describe them in the readme.  off the top of my head -- 

- set deployment target to 11.0
- add "Privacy - Camera Usage Description" with a string to the plist
- add Arkit framework to linked frameworks

I think steps for making a new project or updating an existing project should be documented -- the PG uses a template and I think some settings get overwritten when you update. 

I'll take a look, there might be a way to pass in more specific settings so this stuff doesn't have to get changed manually.  in the meantime, notes about this would help !

**Comment by sortofsleepy** [comment]
Good reminder! I had some of that written down in develop which was just merged with master this morning. But I definitely forgot about the default deployment target settings as well as needing to add the ARKit framework. 

I actually didn't know you could update projects through the project generator so a note about that has been added as well.

Thanks again!
