### ISSUE TITLE
ofxiOSAppDelegate.h / ofxiOSViewController.h not found

### ISSUE THREAD

**Issue by heaversm** [sortofsleepy/arkit-tests#13]
Tried adding these to addons but this generated further errors from within ofxiOS. Any idea on how best to include these?

**Comment by n-rafael** [comment]
I ran into this sort of issue before realizing I was using the OSX deployment of openframeworks rather than the iOS one. Hope this helps!

**Comment by sortofsleepy** [comment]
Hey @heaversm ! 

@nrabreu might have the right answer, are you sure you grabbed the right release of openFrameworks? I don't believe you need to manually add ofxiOS anymore, as long as you download the ios version of oF you should be good to go(note that it's linked in the readme). 

If that didn't work, can you provide more info?

**Comment by heaversm** [comment]
Thanks for the quick response. Worked perfectly.
