### ISSUE TITLE
Twitchiness in examples

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#16]
I noticed that there is some twitchiness to the planes that get added to the scene. I was able to especially trigger this by rotating my phone sideways into landscape orientation. When I do that their rotation flickers back and forth a bit. It also happens pretty often when you look at planes placed in the scene at more glancing angles. 

It seems to happen to the planes at different times, which was curious to me because I thought that if it was something ARkit was doing based on the current camera position it should happen to all the planes at once. 

Long story short, I think I tracked it down to the ofScale(0.0001) call. Not sure why this is happening but removing the call and just drawing my planes much smaller fixes it. So now when I do my draw I do something like this

````
for(int i = 0; i<mats.size(); i++){
        ofPushMatrix();
            ofMatrix4x4 tempMat;
            tempMat.set(mats[i].columns[0].x, mats[i].columns[0].y,mats[i].columns[0].z,mats[i].columns[0].w,
                        mats[i].columns[1].x, mats[i].columns[1].y,mats[i].columns[1].z,mats[i].columns[1].w,
                        mats[i].columns[2].x, mats[i].columns[2].y,mats[i].columns[2].z,mats[i].columns[2].w,
                        mats[i].columns[3].x, mats[i].columns[3].y,mats[i].columns[3].z,mats[i].columns[3].w);
        
            ofMultMatrix(tempMat);
        
            ofSetColor(255);
            ofRotate(90,0,0,1);
        
            //  magic numbers for scale
            float aspect = float(ofGetWidth()) / float(ofGetHeight());
            ofTranslate(0, 0, 0.21);
            img.draw(-aspect/8,-0.125,aspect/4,0.25);
        ofPopMatrix();
    }
````

There's got to be a better way to accurately figure out the real world screen size, but for now this works.

**Comment by ofZach** [comment]
that makes a ton of sense -- I think all the shakiness generally is floating point related  (ie, floating point precision).  arkit coordinate system is in meters (AFAIK) so it makes sense to think about what we draw relative to that vs all the scaling.   I think I threw ofScale() cause I had no idea why everything I drew was so big when first messing with ofxarkit :)

**Comment by sortofsleepy** [comment]
Nice find! I've definitely seen this too but haven't been too sure on where or how to start debugging. I can at least remove the scaling from the samples. 

@aferriss I'm not entirely sure what you mean by needing to find the real world screen size, is 
` float aspect = float(ofGetWidth()) / float(ofGetHeight());` not returning the expected value?
I can look into that if `ofGetWidth` etc aren't bringing in the right values, I did notice that the nightly oF build returns different values than the current release version.

**Comment by aferriss** [comment]
@sortofsleepy It's more that we want to know the actual dimensions of the device in inches (or cm) to calculate the size a full screen image plane should be.  getWidth() and getHeight() are just returning pixel values, but since different devices have different pixel densities, this isn't a reliable way to calculate screen size. 

Annoyingly, apple provides no public api for querying screen ppi. Looking at other questions about this same thing, seems like the solution is to detect the device and then just use a hard coded value based on which device you're dealing with. [See here](https://stackoverflow.com/questions/28573639/how-do-ruler-apps-stay-accurate-on-all-devices)

**Comment by sortofsleepy** [comment]
ah gotcha - hmmmm that is a bit of a pain to hardcode everything but if a method doesn't exist then I guess we got no choice. I dug through a bit and found some already written code, I may just use that.

In the meantime, though I don't know how well it works ,in `develop` I've added a method `getDeviceDemensions` in `ARUtils`. This should pull the correct pixel resolution for the device at the very least(well at least the official device resolution from Apple anyways).

**Comment by ofZach** [comment]
if it's helpful

https://github.com/detroit-labs/IRLSize

in particular this uses a bunch of constants to help provide size info

https://github.com/detroit-labs/IRLSize/blob/master/Pod/Classes/iOS/UIDevice%2BIRLSize.m

I'm not sure how necessary it is for ofxArkit to provide this but if you are trying to size things relative to the screen it's super helpful to know exactly how big the screen is.   I've found projecting the 4 corners of the screen via the camera transform to be useful for mapping screen touches to 3d positions, if you are making a drawing app, etc.

**Comment by ofZach** [comment]
one note on twitchiness (not sure if this is related) -- I've found it helpful to adjust (in OF core) the precision on the programmable renderer's internal shader code-- moving some mediump to highp....  this helped make things a lot more stable for me and less glitchy / twitchy...

**Comment by sortofsleepy** [comment]
closing since there hasn't been much discussion in a long time. If you are still experiencing twitchiness, please open a new issue.
