### ISSUE TITLE
ARKit API changes with Xcode 9 GM

### ISSUE THREAD

**Issue by lossless** [sortofsleepy/arkit-tests#17]
Hi, I updated to the freshly-released Xcode 9 GM, then started getting build errors with the latest example apps. It looks like these 2 changes are needed due to ARKit API changes.

1. ARCam.mm

```
    ARCameraMatrices ARCam::getMatricesForOrientation(UIInterfaceOrientation orientation,float near, float far){
        
        cameraMatrices.cameraView = convert<matrix_float4x4,ofMatrix4x4>([session.currentFrame.camera viewMatrixForOrientation:orientation]);
        
        // ARKit API has changed as of Xcode 9 GM
        //cameraMatrices.cameraProjection = convert<matrix_float4x4,ofMatrix4x4>([session.currentFrame.camera projectionMatrixWithViewportSize:viewportSize orientation:orientation zNear:near zFar:far]);
        cameraMatrices.cameraProjection = convert<matrix_float4x4,ofMatrix4x4>([session.currentFrame.camera projectionMatrixForOrientation:orientation viewportSize:viewportSize zNear:near zFar:far]);
        
        return cameraMatrices;
    }
```
2. MyAppViewController.mm (you already had this marked as a todo)

```
- (void)loadView {
    ...

    // ARKit API has changed as of Xcode 9 GM
    // TODO should be ARWorldTrackingConfiguration now but not in current API(might need to re-download sdk)
    //ARWorldTrackingSessionConfiguration *configuration = [ARWorldTrackingSessionConfiguration new];
    ARWorldTrackingConfiguration *configuration = [ARWorldTrackingConfiguration new];

    ...
}
```

Thanks for this addon. Cheers.

**Comment by sortofsleepy** [comment]
Thanks for catching that @lossless! 

A nice person coincidentally enough filed a PR this morning to help fix this very thing, but unfortunately filed it against the wrong branch. 

I'm gonna wait to see if he/she re-files the PR like I suggested, if not I'll run through and fix this, was planning to double check things anyways now that we're at GM level this week. Will leave this open till one of those two things happens.

**Comment by sortofsleepy** [comment]
So sadly, the potential contributor never re-filed so I just went ahead and changed everything. It's in `develop` now, I will merge all the changes into `master` sometime over the weekend. 

Thanks again for the heads up!
