### ISSUE TITLE
Example ideas 

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#20]
It's just a personal preference but I am not super comfortable with the photo capture example being part of the examples of this addon.  I think examples should help people understand the API or what's possible but not necessarily help copy an aesthetic style.  It's just a preference -- it's your addon and I'm super appreciative of your work on this.

**Comment by sortofsleepy** [comment]
Hey @ofZach !

Ah, I hadn't thought of it that way, I appreciate the input. After first seeing the experiments you and Adam were making(I don't know if he's posted it publicly somewhere but he showed me a neat example he made; different but along the same train of thought) I thought it'd be a good exercise to try out myself; after figuring out the basic gist of it I thought it'd make a good example to show ways of working with the API. 

I'm happy to take the photo capture example down and replace it with something else, though the problem now is thinking about what to replace it with. Do you happen to have any ideas off-hand that might be good without coincidentally copying someone's style? 

Thinking of ideas happens to be my personal hell haha - on top of all the thoughts spinning around from web dev world I have to deal with during the day getting in the way, I've just been terribly self-critical of everything I come up with lately 😅 

(sidebar : planning to do another merge into master, likely some time tomorrow, will make sure to remove the example then)

**Comment by ofZach** [comment]
thanks!  I think it makes sense w/ examples to help show certain problems people might want to solve and leaving them open enough so that people can push them in different direction.  I think it's definitely not hard to make the leap to taking photos and leaving them in space once you are recording other things in space, but I think it's nice to let people take the leap themselves then making a demo which kind of makes that leap for them -- it's just about leaving enough space for imagination.  

personally, I think mapping screen position to coordinate space is helpful (and hard to do given different screen sizes) and horizontal plane detection demos are really useful -- maybe examples in that territory ?   Even something OF's 3d primitves?  Maybe a demo that helps give you a diagnostic view of the device, the origin and some graphical elements in 3d (with aerial, side views, etc) 

Again, it's totally up to you on this, just giving my 2c -- from having worked on OF and made a bunch of the earliest examples, I just feel like examples should be kind of bare-bones and somewhat plain but explanatory.  The space for art and creativity comes from imaging how to connect the dots in new ways.

**Comment by lossless** [comment]
I agree with Zach that a building-block example like a horizontal plane detection demo would be helpful, and his points about example code in general being more of jumping-off points. I think photos posed in AR space may be on the borderline as it was demoed in June during the WWDC onstage, and the video of the demo (Introducing ARKit: Augmented Reality for iOS) with visible source code has been linked from the official Apple Developer ARKit page (https://developer.apple.com/arkit/). It may be helpful to have an ofxARKit example that shows how you can achieve the same with oF.

Thanks to both of you for your work on oF + ARKit.

**Comment by sortofsleepy** [comment]
Thanks for the suggestions @ofZach and @lossless - I'll certainly think about that and try to come up with something along those lines. 

(PS Zach - I've removed the photo example FYI)

**Comment by aferriss** [comment]
This is closed but as long as we're talking about examples, I thought one that might be nice to see is code that uses the lighting estimate with oF to properly shade a model. I haven't looked into the ARLightEstimate yet but seems like it would be handy to see this done!

**Comment by sortofsleepy** [comment]
Ah - heh I guess I closed this too early without thinking haha. Apologies!

But thanks for the input Adam! I haven’t looked too much into lighting estimations either other than seeing that lighting is measured in lumens. Not sure how’d the converted value would work but definitely something to think about.

**Comment by sortofsleepy** [comment]
closing to prune but may revisit later
