### ISSUE TITLE
Face ID? Yay? Nay?

### ISSUE THREAD

**Issue by sortofsleepy** [sortofsleepy/arkit-tests#28]
To anyone that might be paying attention  : 

Now that iPhone X is out(or sort of getting to folks) - is using the front facing camera of any concern to anyone? I won't be getting one (I just can't fathom paying 1k for a phone) but the adjustments to accommodate Face ID seem pretty straightforward I could probably add that in with little trouble(PRs are great too!).

If no one responds I'll just assume it's not important! 😛

**Comment by sortofsleepy** [comment]
https://developer.apple.com/documentation/arkit/creating_face_based_ar_experiences

**Comment by aferriss** [comment]
Seems like it could be a great for those that have the X. I'm in your camp and probably won't shell out. Who knows what the future holds though, it's possible all future iPhones could have the depth sensor.....

**Comment by sortofsleepy** [comment]
Yea, future-proofing is a good idea, I guess I was just wondering how in-demand this might be at the moment to weigh where I ought to focus efforts on as I know I haven't been able to keep a steady pace of fixes + new things. 

I really wish they'd open up depth tracking to the back camera as well - AVFoundation can be set up to capture depth information. Oh well 😞

**Comment by sortofsleepy** [comment]
Ok! To anyone interested, I've finally gotten around to adding FaceID stuff - full disclosure though : **THIS HAS NOT BEEN TESTED!** Reason for that is - I don't have an iPhone X and managed to not cave into the peer pressure after a month and a half 😛  The code was pretty easy to add in, hence the reason for me doing so anyways. 

When initializing ARKit, there is a different session configuration that is used.
```c++
  ARFaceTrackingConfiguration * config = [ARFaceTrackingConfiguration new];

```
I haven't found anything concrete to suggest otherwise, but it looks like you loose plane detection capabilities when using the face detection... makes sense but I imagine at some point vertical plane detection will come into play at least.  All the other available configuration options seem to be available. 

There is a new struct called `FaceAnchorObject`. ARKit provides vertices, uvs and indices for a face, the struct is able to take that data and build a mesh if you want, obviously of course you can use the data however you'd like. 

You can utilize face data through the ARAnchorManager class, which now contains an `updateFaces` function. The code is pretty similar to the `updatePlanes` function and handles all the necessary conversions, etc, to oF friendly formats. Should be ok code, but looking at it again right now I think I made an error calculating indices. I'll have to take a look again at a later point.
