### ISSUE TITLE
Mystery Framerate drop in newer version

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#29]
I'm not sure at what point this happened, but somewhere along the way I noticed the addon started getting a worse framerate. You can test this by building the most recent, which on an iPhone SE gave me around 40fps, and then building an older (I tried 2b98adc703a0c96c9c883d1feec984d4289674ca) and you'll get a smooth 60fps.

Will try and do some more investigating, but wanted to see if anyone else had noticed this or if I'm just imagining things...

**Comment by sortofsleepy** [comment]
Oh no... 😓 , I'm sorry dude. 

I am oddly still seeing 60fps(on a 6S) though hmmm... 

The only real major change I can think of is changing up how the camera image is drawn. It's now using a VBO and the UVs are constantly being updated like in the default Metal example. 

If you comment out `updatePlaneTexCoords` in `ARCam::update` does that make a difference? (note - image might look weird though)

another thing I might try is just dropping in the old `ARCam.h/ARCam.mm` files + `ARShaders.h` and see if that does the trick, then we know I messed up somewhere updating the camera image. 

If it's not there, then I'll need a little more help to do some more digging

**Comment by aferriss** [comment]
Hmm, I'm not seeing a difference using the ofMesh vs. ofVbo or commenting out updatePlaneTexCoords. I did some profiling and didn't notice anything out of the ordinary. It looks like the ARKit thread is doing most of the lifting and the heaviest thing happening in the ofApp is the image being drawn to the screen. 

Maybe we can close this for now since it only seems to be me. Starting to think it might just be the SE being slow on the ARKit thread.

However, I did also notice a bug with the example where it will add and remove anchors without any touch input. I reverted back to a clean master so I'm sure this isn't because of any tinkering. It only  happened when I was pointing the phone at the floor at about a 45 degree angle (I know this sounds crazy). It even happens when you comment out the addAnchor() in the touch event. Usually happens in this order

After 15-20 seconds an anchor is added
Another 15-30 seconds later a second anchor appears
15-30 seconds later the second anchor is removed

**Comment by sortofsleepy** [comment]
Cool - sounds good. I'm gonna close this for now, but feel free to bring it up again if it keeps happening. I did test a little more to try and see if I could reproduce this anchor thing just now and there's definitely something weird; I let things run for about 10,000 frames and while the fps was pretty constant at around 60fps, it did dip once or twice to the 40s. I'll keep an eye on it too. 

As for the anchors, I unfortunately wasn't able to re-produce that. Did the same thing happen after commenting out `[session addAnchor:anchor]`? Do open another issue if it's still happening.

**Comment by aferriss** [comment]
Yep, I commented out all instances of `[session addAnchor:anchor]` in the anchor manager and it still happens. I'll open another issue.
