### ISSUE TITLE
enable depth for examples

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#3]
unless there's a strong reason, it might be better to enable depth in all examples here: 

https://github.com/sortofsleepy/ofxARKit/blob/master/example-setup/src/main.mm#L8

and just disable / enable depth testing with ofEnableDepthTest() etc, otherwise there's no chance for depth testing and I think depth testing is kind of important for AR graphics.

**Comment by sortofsleepy** [comment]
Good catch! No strong reason really for having it disabled, I was just copying the example project in the release back when I started this. 

I've switched it on in the sample, also note that the name of the sample has changed as something got borked when I was quickly setting it up :(
