### ISSUE TITLE
Building a face mesh?

### ISSUE THREAD

**Issue by cwervo** [sortofsleepy/arkit-tests#39]
I'm working on a minimal example for face tracking on the iPhone X. I made the changes @ofZach  outlined in #32 but both of the following:

```c++
        face.rebuildFace();
        face.faceMesh.draw();
```

```
        mesh.addVertices(face.vertices);
        mesh.addTexCoords(face.uvs);
        mesh.addIndices(face.indices);
        mesh.draw();
```

produce this strange little mesh around the eye:

<img width="476" alt="screen shot 2018-03-08 at 1 23 50 am" src="https://user-images.githubusercontent.com/5826638/37143622-919956ca-2270-11e8-93b0-ce83ad72039e.png">

It seems like the `face.indices` vector is the problem here, as it only contains four numbers for me:
```
[1201, 44, 45, 1200]
```

By commenting out the call to `addIndices` & rendering a mesh of the vertices with `OF_PRIMITVE_LINE_STRIP` we can see the vertices order doesn't seem organized by nearest neighbor:

<img width="469" alt="screen shot 2018-03-08 at 1 26 12 am" src="https://user-images.githubusercontent.com/5826638/37143665-ae5ad1bc-2270-11e8-8a2b-7745223bf9c5.png">

and by coloring (via HSB) the lines by their index, we can see this strange path even clearer:

<img width="470" alt="screen shot 2018-03-08 at 1 29 07 am" src="https://user-images.githubusercontent.com/5826638/37143693-c16f04e4-2270-11e8-8131-ebd35b726144.png">

Even this colored rendering gets collapsed down to the small square if I uncomment `mesh.addIndices(face.indices);`:

<img width="468" alt="screen shot 2018-03-08 at 1 30 09 am" src="https://user-images.githubusercontent.com/5826638/37143746-e6b33d56-2270-11e8-9069-0bb95307e294.png">

Any thoughts on why I'm getting such strange output? Thanks!

-------

Also, as an aside, I noticed you're not going to be able to work heavily on this project anymore. I'd be happy to be granted collaborator access & start helping out, I've been digging into this project a lot recently & will be depending on it for prototyping for a while!

**Comment by ofZach** [comment]
I am not sure what you are seeing but one thing to be careful about is that drawWireFrame with ofMesh on iOS is super broken with indices, I think you have to draw by hand in order for things to make sense.   

The mesh produced by arkit contains points that are way out of order -- you can't connect them by nearest neighbors - you have to use indices. 

For debugging I found actually printing the entire mesh (vertices, indices) to the console (via json) and loading into desktop OF kind of helpful -- I was able to zoom in on the mesh and see what points correspond to what.

**Comment by ofZach** [comment]
if it's helpful, here's a zip of my working copy of ofxArKit where I poked around and got face tracking to work with the changes I described 

https://www.dropbox.com/s/tq7aq9q90ajtny0/src.zip?dl=0

you can see a lot of places where I print stuff out etc...  haven't had time to do a proper PR or clean this up...

you should see a ton of indices but again, drawWireframe will not help you debug the mesh -- use indices and draw indices/3 number of triangles by hand to see the mesh (in wireframe)

**Comment by sortofsleepy** [comment]
hey @AndresCuervo !

As you might have already surmised Zach knows way more about this aspect than me haha. I'll let him take it from here,

On another note I just added you as a collaborator. Thanks for being willing to help! It's not that I can't work on this heavily forever - at the moment I'm in New York without access to my Mac. I kinda have access to one but there are a couple of issues that prevent me from doing any real work, it's really only good for checking for errors in code 😢 

Please remember to read the guidelines in the Wiki before you push any code, it's a bit generalized and I need to make things a little more specific but it should hopefully be clear enough. Feel free to ask questions if you're unsure.

**Comment by cwervo** [comment]
Hey @ofZach, thanks so much for your help! I dropped your src in & it works well - looks like you’re already adding the indices correctly with this bit: 

```c++
for(NSInteger i = 0; i < geo.triangleCount*3; ++i){
                        int16_t ii = geo.triangleIndices[i];
                        faces[index].indices.push_back((int)ii);
                    }
```

Which replaces [this line](https://github.com/sortofsleepy/ofxARKit/blob/master/src/ARAnchorManager.mm#L269) which calculates single indices, not triangular indices!

> I am not sure what you are seeing but one thing to be careful about is that drawWireFrame with ofMesh on iOS is super broken with indices, I think you have to draw by hand in order for things to make sense.

Turns out your `src` above, which does the “by hand” part in the addon method, means that I can simply do:

```c++
mesh.addVertices(face.vertices);
mesh.addTexCoords(face.uvs);
mesh.addIndices(face.indices);
mesh.draw();
```

that + animating color gets me my desired result:

![rainbow_face_centered_anim_clipped](https://user-images.githubusercontent.com/5826638/37186700-a2f8b1b4-22fb-11e8-93c0-afa5bca85bd9.gif)

Which is really convenient! Also, with the correct indices now, `mesh.drawWireframe();` even works!

![screen shot 2018-03-08 at 5 46 06 pm](https://user-images.githubusercontent.com/5826638/37186719-b20f48c0-22fb-11e8-9428-609e12ecf064.png)

One final mesh related task I haven't been able to figure out yet though @ofZach: how do I map the texture of the face to the mesh? When I naively try to bind the camera I get the following:

![inverted_camera_texture](https://user-images.githubusercontent.com/5826638/37187015-30fd707a-22fd-11e8-9c08-1712d686aa5b.gif)

Any help here would be very appreciated!

**Comment by ofZach** [comment]
I don't think there's a perfect way to do this.  When I did it, I projected the 3d points to 2d and then used those 2d points to get texture coordinates.

**Comment by cwervo** [comment]
Also, @sortasleepy thanks for adding me! Once I figure out a few more prototyping issues I plan on make a PR that contributes an example for this!

**Comment by ofZach** [comment]
re: drawWireFrame --  note the missing lines :)   it doesn't do all triangles since there are some issues on ios with drawWifeFrame and meshes

<img width="319" alt="screen shot 2018-03-09 at 10 42 52 am" src="https://user-images.githubusercontent.com/142897/37198346-afd88234-2386-11e8-8554-aa9064d4c82d.png">

**Comment by cwervo** [comment]
Ah yeah, didn't catch that the first time, thanks Zach!

**Comment by cwervo** [comment]
Hey @ofZach is it okay if I incorporate the changes from that Dropbox `src` directory into a PR? I'll try & wrap up an example project + merge in the changes to make the faces public (basically your changes in the linked `src`), if you're fine with me using that code!

**Comment by sortofsleepy** [comment]
cleaning stuff up a bit and closing this now that the changes have been merged in and also due to lack of activity . If more discussion is necessary and no other bugs have been uncovered, please shift to another medium.
