### ISSUE TITLE
#define to disable face tracking

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#40]
I think, (not 100%  sure), that if your app includes arkit related code to face tracking then your app store submission needs to have a privacy policy or may be rejected.  It might be good to have this as a #define so that it's easy to just comment out these symbols.

**Comment by sortofsleepy** [comment]
hmm... not quite sure I follow (not the privacy policy part - I can look into that later). 

The session configuration helper doesn't immediately enable face tracking by default - you have to call `.enableFaceTracking` to change the necessary flag on the session configuration. If people setting up the sessions manually, taking care not to enable face tracking would basically be up to them no? 

Or were you suggesting a `#define` statement to comment out the face tracking code?

**Comment by ofZach** [comment]
I feel like a #define is needed since even though you don't use face tracking the symbols are there but I could be wrong

https://forum.unity.com/threads/submitting-arkit-apps-to-appstore-without-face-tracking.504572/

the idea would be a #define completely avoid including any face tracking code symbols in your app

**Comment by sortofsleepy** [comment]
ah, gotcha - yea that sounds like it might be necessary. Really silly of Apple though. I can take a look 👍

**Comment by sortofsleepy** [comment]
closing this as this is finally resolved in `master`
