### ISSUE TITLE
z-fighting on depth test

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#5]
I don't know if this is specifically a ofxARKit thing or an ofxIOS thing but I get a lot of z-fighting on overlapped graphics as I move away from them (it's much better when I move closer).  I tried switching up the renderer  as I had to switch to es1 for this example, since I was reading the screen back to textures and I couldn't get that to work on es2: 

https://twitter.com/zachlieberman/status/897945041573879808

without much luck in seeing z-depth fighting improve.   

as I was making this issue, I just noticed the this near and far values here: 

https://github.com/sortofsleepy/ofxARKit/blob/develop/src/ARProcessor.h#L113

and will experiment to see if there's ways to improve this with adjusting these values, etc  (I am using older code which is closer to the example I posted in a previous issue)

**Comment by ofZach** [comment]
definitely alternating the near and far values help -- it looks like these have changed since this issue originally posted?

**Comment by sortofsleepy** [comment]
@ofZach - 💦  😓   I did a bunch of cleanup and added a bunch of new files, but `getMatricesForOrientation` SHOULD still be in `ARProcessor`; I don't recall changing the function, can you point to where you see something different? (apologies if I messed up your workflow! 🙇 )

My original goal when I was just starting out was one class, but as time went on it seemed better to split things out into different classes depending on what functionality was desired. 

And glad to hear tweaking near/far works, is there a better default value that ought to be set?

**Comment by ofZach** [comment]
yeah it might have been my code not your I'm referring to -- I had this line in the zip I uploaded to a previous issue where I kind of hooked up some things to get things working: 

            simd::float4x4 projectionMatrix = [session.currentFrame.camera projectionMatrixForOrientation:UIInterfaceOrientationPortrait viewportSize:_viewportSize zNear:0.001 zFar:1000];

but I think the 0.001 is a bit problematic (I just took a look and it looks like I grabbed it from the arkit metal example)...  my intuition is that 0.01 is better but haven't experimented fully...

**Comment by sortofsleepy** [comment]
Cool, that's fine - I think for now, maybe the way forward is to set the default to 0.01 and then add setter functions to tweak near and far(also add those as properties)?

**Comment by sortofsleepy** [comment]
Default has been set to 0.01 - will add setters at another point sometime soon.
