### ISSUE TITLE
ARKit 2.0 (!)

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#50]
Looks like it's that time again (or at least it was a couple weeks ago), I thought I would open this just as a starting point for discussing the [new features](https://www.apple.com/newsroom/2018/06/apple-unveils-arkit-2/) in 2.0. 

Here's a list of the newly added features and their accompanying guides / docs
1. [World map](https://developer.apple.com/documentation/arkit/arworldmap?language=objc)
1-1. [multi-user AR](https://developer.apple.com/documentation/arkit/creating_a_multiuser_ar_experience?language=objc) 
1-2. [persistent tracking](https://developer.apple.com/documentation/arkit/arworldmap/archiving_world_map_data_for_persistence_or_sharing?language=objc)
2. [Environmental Reflections](https://developer.apple.com/documentation/arkit/arenvironmentprobeanchor?language=objc)
3. [Object Detection and Scanning](https://developer.apple.com/documentation/arkit/scanning_and_detecting_3d_objects?language=objc) more on [scanning here](https://developer.apple.com/documentation/arkit/arobjectscanningconfiguration?language=objc) and [detecting here](https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2968177-detectionobjects?language=objc) and [here](https://developer.apple.com/documentation/arkit/arobjectanchor?language=objc) and [here](https://developer.apple.com/documentation/arkit/arreferenceobject?language=objc)
4. A new [image tracking mode](https://developer.apple.com/documentation/arkit/arimagetrackingconfiguration?language=objc)

Also looks like some of these features will need the [multipeer connectivity framework](https://developer.apple.com/documentation/multipeerconnectivity?language=objc)

There's also the new 3d file format "usdz", which might need a loader if people are interested in using it. It's not clear to me if some of these new features request models in that format but I imagine it wouldn't matter as long as you have the 3d data. I couldn't find much info on the specifics of usdz though.

The 3d scanning and detection sounds really cool and I'm super excited to see progress on this (I mean actually multi-user and persistence seems cool as well :D ). @sortofsleepy Would it be helpful for me to make some of these features individual issues for people to pluck off if they'd like to contribute? Should we shoot for implementing all of these or just some? Thoughts?

**Comment by sortofsleepy** [comment]
Gosh I had only heard bits and pieces - I guess I was so heads down with what I was doing at the time I didn't realize there was so much released. Man always playing catch up haha. 😅 

@aferriss yea - that's actually not a bad idea, if you wouldn't mind doing making issues for everything. 

I think one more thing at this point to think about given all the new features, and this is really more on the lower priority side of things, is to re-org all the files into folders I can get around to that at some point but if someone wants to tackle that that could be a good beginner issue to go through for anyone out there that might want to contribute somehow. 

I'll try to get caught up this week and clean things up.

**Comment by aferriss** [comment]
@sortofsleepy Sure, I'll try and piece some issues together and hopefully we can get the ball rolling on these!

**Comment by aferriss** [comment]
Oh, I also missed some other new features only available on iphone X. 

There is now eye gaze tracking with [lookAtPoint](https://developer.apple.com/documentation/arkit/arfaceanchor/2968192-lookatpoint?language=objc)

and also an additional feature for the face tracker for [detecting if the tongue is out or not](https://developer.apple.com/documentation/arkit/arblendshapelocationtongueout?language=objc)



I found a good round up with example videos on the [unity blog](https://blogs.unity3d.com/2018/06/14/whats-new-in-unity-arkit-plugin-for-arkit-2/)

**Comment by sortofsleepy** [comment]
Closing this to clean up - will move to Github projects format to preserve content
