### ISSUE TITLE
File reorganization

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#51]
As mentioned in https://github.com/sortofsleepy/ofxARKit/issues/50 it would be nice to reorganize the files in the src folder of this project in a more meaningful way. 

@sortofsleepy Did you have any thoughts on what this might look like? Following the template of ofxCv for instance would look like:

docs
example-*
libs
--ofxArkit
----include
------all the .h files from old src folder except ofxARKit.h
----src
------all the .mm files from old src folder
       
src
--ofxARKit.h

**Comment by sortofsleepy** [comment]
Hmm - I'm really open to anything, if I had one opinion I'd say that perhaps it's less important to organize things into header / implementation files; I was thinking things could be organized more into categories ie 

docs
example-*
libs
--ofxARkit
----camera
----networking

and so on and so on.

**Comment by sortofsleepy** [comment]
closing to prune but may revisit later
