### ISSUE TITLE
Should change namepace ARCore

### ISSUE THREAD

**Issue by sortofsleepy** [sortofsleepy/arkit-tests#58]
Probably ought to change this namespace at some point so people that might be working with Google's ARCore at the same time won't get confused.

**Comment by cwervo** [comment]
Agreed but do you have any thoughts on what it should be changed to? I'm having trouble coming up with a different name to encompass what the namespace is.

**Comment by sortofsleepy** [comment]
@AndresCuervo been thinking about this and I think the easiest way would be to maybe drop the "AR" portion and prefix everything with `ofxARKit` so it'd be like

`ofxARKit::core::<function>`

**Comment by sortofsleepy** [comment]
started making some changes around this

**Comment by sortofsleepy** [comment]
closing for now to prune but may re-visit later
