### ISSUE TITLE
horizontal plane detection

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#6]
it would be great to add detected horizontal planes to this addon -- arKit can give you info about planes as it finds them (https://blog.markdaws.net/arkit-by-example-part-2-plane-detection-visualization-10f05876d53) which might useful if you have content that specifically needs to appear on a floor or table, etc and for getting a base of reference.

I didn't look super hard into this but I have only seen examples that use scene kit that do this and I tried porting one of these over without much luck....

**Comment by stc** [comment]
I have no device at hand to send test images, but I was playing around with them the other day. Planes are special anchors (having center & extent vectors) that I was able to access like this:

`
void ARProcessor::drawPlanes() {

     cam.begin();
     applyMatrixOnCam();
     
     for(int i=0; i < [session.currentFrame.anchors count]; i++ ) {
        if([session.currentFrame.anchors[i] isKindOfClass:[ARPlaneAnchor class]]) {
            ARPlaneAnchor* pa = (ARPlaneAnchor*) session.currentFrame.anchors[i];
            
            ofMatrix4x4 anchor_transform = convert<matrix_float4x4, ofMatrix4x4>(session.currentFrame.anchors[i].transform);
            ofVec3f center = convert<vector_float3,ofVec3f>(pa.center);
            ofVec3f extent = convert<vector_float3,ofVec3f>(pa.extent);
            
            ofPushMatrix();
            ofMultMatrix(anchor_transform);
            ofFill();
            ofSetColor(255);
            ofRotateX(90);
            ofTranslate(center.x,center.z);
            ofDrawRectangle(-extent.x/2,-extent.z/2,0,extent.x,extent.z);
            ofPopMatrix();
        }
    }
    cam.end();
}
`
However I might mess up something, since the result is not as reliable and precise as on the example you mention

What do you think, a c++ like api, like the cinder-metal arkit here https://github.com/felixfaire/Cinder-ARKit/blob/master/include/CinderARKit.h might make sense..?

**Comment by sortofsleepy** [comment]
I'd be really surprised if this ended up being the answer cause Apple's docs make it seem like it's not absolutely necessary, but perhaps delegate methods might be needed now to get accurate plane tracking? [See here](https://developer.apple.com/documentation/arkit/arsessiondelegate/2865624-session?language=objc).

I'll try giving things a whirl over the weekend on this, I had an idea for a silly toy ARKit project I'm looking to start that could make use of plane tracking. 

As far as an api - I'm open to the idea of something more formal as long as it's straightforward enough. Open to suggestions on the design of one!

**Comment by JotaroS** [comment]
Hi there,

I also wanted to try plane detection and found that anchor point is added, when plane is detected in the scene. I know that it's not that accurate like example.
On the other hand I've found that when tap the screen to manually add anchors the example app crashes.
Should I post another issue for this or is there any solution to this?

Thanks, 
Joe

**Comment by sortofsleepy** [comment]
@JotaroS - which branch are you cloning from? `develop` should work and SHOULD be the default(unless github changed something), `master` might still be still have bugs. At some point I'll merge what's working into `master`
And yes, please file a another issue next time, otherwise things will get confusing.

**Comment by sortofsleepy** [comment]
So I gave this a shot and not really any luck either :/ 

but a quick heads up - I rolled stc's code into the codebase and made it part of an AnchorManager class, that might be a good place to keep working from.

**Comment by stc** [comment]
it sort of works & accurate: https://twitter.com/_stc/status/900365392337448960
however i am kind of unable to turn it on/off which results to a jumping behavour, repositioning content, since the plane parameters are changing continuously

**Comment by sortofsleepy** [comment]
I've added a setting to turn on/off updating and merged into develop. I'll leave this open for now until I've tested more in depth

**Comment by sortofsleepy** [comment]
I've tested a bit and the switch mostly works. Logically it should work but I'm still seeing some odd behavior. Will continue to test.

**Comment by sortofsleepy** [comment]
Finally had a little bit of time to work more at this - updated the plane tracking code with 388efab on develop and I think it's working a lot better. I'm gonna close this for now but I still haven't managed to find a moment to do any extensive testing, please do feel free to re-open if it still needs work.

Will merge into master in the (hopefully) not to distant future.
