### ISSUE TITLE
Camera image texture not working?

### ISSUE THREAD

**Issue by cwervo** [sortofsleepy/arkit-tests#61]
I tried out `example-basic`, `example-image-recognition`, and `example-face-tracking` and while the tracking works well & virtual objects get drawn the camera feed in the app is gray for me & I get this warning in the XCode console:

```
Failed to create IOSurface image (texture)
2018-09-17 11:34:25.187191-0700 example-basic[2632:615621]
```

![screen shot 2018-09-17 at 11 34 29 am](https://user-images.githubusercontent.com/5826638/45642706-e28ea180-ba6d-11e8-9cc1-8689866a5263.png)

---

For reference, here is what `example-basic` looks like:

![screenrecoding_arkit_gray_camera_texture](https://user-images.githubusercontent.com/5826638/45643988-42d31280-ba71-11e8-917e-12baad8ccb9b.gif)

The OF logo planes appear & track correctly whenever I tap, but as you can see the rest of the scene is gray, not the camera image texture.

**Comment by cwervo** [comment]
Oh, also, I'm on an the iOS 12 beta so it might be that & not the fault of the addon, but it would be helpful if someone else could confirm that this works on iOS 11.x!

**Comment by sortofsleepy** [comment]
hmmmmmm, that's really weird cause I know it was working ugh(at least on iOS 11)... but I haven't looked at the code in awhile, it's possible I missed something. 

Couple of things to try. 
1. Does this project work for you? I can't quite remember the setup but I believe you could just drop this into the oF apps folder. 
https://github.com/sortofsleepy/metalTextureTest

2. [Here I have a map to line up texture info between Metal and OpenGL](https://github.com/sortofsleepy/ofxARKit/blob/master/src/lib/MetalCam.mm#L31) that was pulled from an Apple example. Looking at the error, the issue is that the texture being generated isn't OpenGL compatible for some reason, do those OpenGL formats still exist on iOS 12? 

I don't have a Mac on me at the moment so this is gonna be troublesome to fix, worst case I'll just revert things to using the old class.

**Comment by cwervo** [comment]
1. When I tried loading metalTextureTest in OpenFrameworks iOS 0.10.0 w/ the `develop` branch of ofxARKit I get some errors, so it's not working for me. <details> <summary>(click to see image of 5 compilation errors)</summary> ![screen shot 2018-09-18 at 2 49 35 pm](https://user-images.githubusercontent.com/5826638/45718508-1c38d880-bb52-11e8-9d24-878e8f371db4.png) </details>
2. Not sure about the specifics but my guess is that [the deprecation of OpenGL ES on all future Apple platforms](https://developer.apple.com/ios/whats-new/#deprecationofopengles) has something to do with this? Perhaps they exist but have to be accessed differently? I know @aferriss has been poking around Metal & rendering in iOS, maybe he might have some insight?

**Comment by sortofsleepy** [comment]
ah re:
1. It's been awhile but I'm pretty sure you don't need to include ofxARKit with the metalTextureTest project, that's probably why you're seeing re-definition errors.  It should just be a test project for rendering the camera

2. Yea that might have something to do with things though I'm surprised they're starting this early - one way you could try checking might be to just see if Xcode autocompletes those definitions. 

It also occurred to me, the texture size could possibly be an issue. If you try logging width and height starting from [here](https://github.com/sortofsleepy/metalTextureTest/blob/master/src/MetalCam.mm#L381), does either value exceed 4096?

**Comment by cwervo** [comment]
1. Hmmm, the project depends on the `ofxARKit` & `ARCore` namespaces explicitly so it does seem to have some conflict. When I remove ofxARKit from the project it errors out on not having `ARCore` in `MyAppViewController.mm`
2.  Yep the XCode 10 beta autocompletes the GL definitions, so they're still there at least.

Running `example-basic` with [this log statement](https://github.com/sortofsleepy/ofxARKit/blob/develop/src/lib/MetalCam.mm#L374) added back in I get:

```
Width is 2250 and height is 4872
```

So yeah, the height is > 4096. Scaling width & height by half there still gives the `not opengl compatible` issue—do you know where I would change this height to see if this is why the texture isn't being created?

**Comment by sortofsleepy** [comment]
That's weird - did you happen to try declaring the namespaces? ~I only did a cursory look over the main app but I don't see anything that depends on other ofxARKit files~ whoops looks like I'm using it to start the session; I'd take out the session code and create it manually, then try just declaring the namespaces in ofApp
```c++
using namespace ofxARKit;
//using namespace ARCore;
```
**Edit - whoops I think the namespace if ofxARKit::ARCore, not just ARCore anymore**
 
In any case it sounds like the texture size is just too large. To be absolutely sure try running 
```c++
int val;
glGetIntegerv(GL_MAX_TEXTURE_SIZE,&val);
```

and see what value gets put into `val`. 

If you wanna play with the width and height for the texture, just adjust those two variables you logged. Sounds like I might need to add a scaling factor of some sort (though I don't know yet what would work for all the devices that support ARKit now :/ )

**Comment by cwervo** [comment]
`glGetIntegerv(GL_MAX_TEXTURE_SIZE,&val) ` does indeed return 4096.

I made [a PR](https://github.com/sortofsleepy/ofxARKit/pull/62) (that I'll merge by the end of the week if no one objects) that adds a simplistic check for either width or height being above this max. It's not the most robust solution but I'd rather dig into this when we have more people willing to test/submitting issues about it. This seems like a good stopgap in the meantime.

**Comment by AndresCuervo** [comment]
I'm getting `GL_MAX_TEXTURE_SIZE` is indeed 4096. I made

**Comment by krahd** [comment]
Hi both,

Thanks a lot for the addon, it's very useful.

I am a bit confused by the implementation. I am trying to get the camera texture (e.g. to take a photo of the user when he or she opens her mouth) but getCameraTexture() is now commented. From what I see there is ARCam that implements it but it's not used?

Any pointers would be most welcomed!

**Comment by sortofsleepy** [comment]
HI @krahd !

Glad you're finding this useful! 

Looking at it now I see I never got around to implementing this fully - my apologies on that. 

So `ARCam` should be considered deprecated - it's using an older method of converting a `CVPixelBuffer` object from IOS which worked, but did have some issues.

It's still there just in case someone might need it still, but things are currently being rendered with Metal instead which provides more stability and makes it a bit easier to get an un-distorted image. The new camera class to use is `Camera.h` and everything is(or at least should be) converted to use the new class.

At the moment, if you feel adventurous, `Camera` does have a method for returning the texture from Metal, it will return a `CVOpenGLESTextureRef`. [You can get an idea of how to use it here](https://github.com/sortofsleepy/ofxARKit/blob/master/src/lib/ARCam.mm#L531), essentially, it's like a regular OpenGL texture. 

If you'd prefer an easier way, you can always render into an ofFbo and extract the texture from that. That might actually be the better way in your case now that I think about it. 

One note on this - if you do use the texture, you will probably have to flip it on the y-axis before drawing. This can be done in a shader, see the shader in `Camera.h` if you're not familiar with how the technique works. 

At the moment I can't finish things as I'm away from home and don't have a Mac around but the plan is to continue a bit more on this when I get home around Christmas. PRs are always welcome if you happen to want to implement a better `getTexture` functionality.

**Comment by krahd** [comment]
Thanks so much for your answer!
Happy to collaborate if my implementation is not too hacky…  :)

**Comment by sortofsleepy** [comment]
closing to clean things up due to lack of responses
