### ISSUE TITLE
metalcam example error

### ISSUE THREAD

**Issue by erikparr** [sortofsleepy/arkit-tests#63]
![image](https://user-images.githubusercontent.com/896122/50518133-60723800-0ab4-11e9-9586-ed8fa0f956ec.png)

on xcode 10.1

**Comment by sortofsleepy** [comment]
Hi @erikparr !

I do not have XCode 10 handy to test at the moment - hopefully someone will be able to chime in until I can. It's an interesting error message if the error is what I think it is. 

Does changing that chunk to 
```c++
   using namespace ofxARKit::core;
@implementation MyAppViewController
   // other code
- (void)loadView {
    [super loadView];
    
   SFormat format;
    format.enableLighting();
    self.session = generateNewSession(format);

  // ... 
```

work? 

Or was this a general note that this needed to be fixed?

**Comment by sortofsleepy** [comment]
Closing to clean up due to lack of response and other reporting.
