### ISSUE TITLE
Add texture to Matte sample

### ISSUE THREAD

**Issue by camjam332** [sortofsleepy/arkit-tests#75]
I'm a little confused on how we can manipulate the sample shader in the new Matte example. I understand that we're getting the rgba values from the camera texture and passing in to the shader in `Camera.h` but I'm having trouble understanding how we implement that into our `ofApp.mm` file. 

Any help would be greatly appreciated!

**Comment by sortofsleepy** [comment]
Hey @camjam332, 

You actually spotted something I somehow completely missed when looking over the PR for this. In short, the segmentation should actually not happen in the middle of rendering the camera image,  I don't know why the submitter decided to do that or tweak the class to automatically render the person segmentation. I will correct that at some point next week. 

What I would do is use the shader in Camera.h as a basis for how to re-render things in your own application. If you look at [the header file](https://github.com/sortofsleepy/ofxARKit/blob/master/src/lib/Camera.h#L163), you'll see there are getter functions for all of the textures needed to do person segmentation. 

Does that make sense?

**Comment by sortofsleepy** [comment]
Gonna close this cause I've prepared the fix; just need to test then merge things in.
