### ISSUE TITLE
No known class method for selector 'supportsFrameSemantics'

### ISSUE THREAD

**Issue by dimitre** [sortofsleepy/arkit-tests#86]
<img width="1307" alt="Screenshot 2024-05-21 at 13 34 41" src="https://github.com/sortofsleepy/ofxARKit/assets/58289/902d4e36-9893-4e4c-ad85-f14f548f1bcd">

**Comment by sortofsleepy** [comment]
Thanks for opening a new issue here.  Just to add a little more context for anyone coming across this 

* According to Dimitre, even adding the ARKit framework doesn't clear the error. 
* Without an  Apple setup at the moment it's a bit hard for me to diagnose, especially given that according to
  [this](https://developer.apple.com/documentation/arkit/arconfiguration/3089122-supportsframesemantics) the method "should" exist.

That said, `SessionFormat`  is pretty much a helper class to make it easier to configure things, it's not a mandatory thing you must use. Its possible to manually create a configuration from which you can derive a session from to then use in your oF app.

If someone out there is up for fixing things, I'm happy to look at PRs to the best of my ability.

**Comment by sortofsleepy** [comment]
Thanks to sadmb, this issue is likely fixed. Going to close for now; if this issue persists, we can reopen things then. 

Fix is currently applied to `develop` branch.
